services:
  mariadb-development:
    image: mariadb:latest
    container_name: mariadb-api-node
    environment:
      MYSQL_ROOT_PASSWORD: dockerpass
      MYSQL_USER: database_docker
      MYSQL_PASSWORD: dockerpass
      MYSQL_DATABASE: database_docker
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:
    driver: bridge
